var geeknavData = {
  site:{
    '综合':[
      {
        'img':'http://img.zcool.cn/community/011b4e569615756ac725af2358c9f2.png',
        'title':'Google',
        'link':'https://www.google.com',
        'detail':'全球最大的搜索引擎'
      },
      {
        'img':'https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon.png',
        'title':'StackOverflow',
        'link':'http://stackoverflow.com/',
        'detail':'一个与程序相关的IT技术问答网站'
      },
      {
        'img':'http://img1.iyiou.com/Company/2016-05-11/cf-segmentfault.jpg',
        'title':'SegmentFault',
        'link':'https://segmentfault.com/',
        'detail':'SegmentFault是中国领先的开发者社区。旨在为中文开发者提供一个纯粹、高质的技术交流平台'
      },
      {
        'img':'http://c.csdnimg.cn/public/favicon.ico',
        'title':'CSDN',
        'link':'http://www.csdn.net/',
        'detail':'全球最大的中文IT社区'
      },
      {
        'img':'http://static.zhihu.com/static/revved/img/ios/touch-icon-152.87c020b9.png',
        'title':'知乎',
        'link':'http://www.zhihu.com/',
        'detail':'中文互联网最大的知识社交平台，XXX是一种怎样的体验？'
      },
      {
        'img':'//gold-cdn.xitu.io/favicons/apple-touch-icon-57x57.png',
        'title':'掘金',
        'link':'https://juejin.im/welcome',
        'detail':'自称是一个只有高手分享的社区'
      },
      {
        'img':'https://toutiao.io/apple-icon-57x57.png',
        'title':'开发者头条',
        'link':'https://toutiao.io/',
        'detail':'程序员界的今日头条'
      },
      {
        'img':'http://blog.jobbole.com/wp-content/themes/jobboleblogv3/_assets/img/jobbole-logo.png',
        'title':'伯乐在线',
        'link':'http://blog.jobbole.com/',
        'detail':'优秀原创文章和翻译文章聚集地'
      },
      {
        'img':'http://cfanz.cn/uploads/png/2014/06/10/10/YL41W69H3C.png',
        'title':'Github',
        'link':'https://github.com/',
        'detail':'全球最大的IT同性交友社区'
      },
    ]
  }
}
